@extends('layouts.admin')
@section('title','Visitor stats')
@section('heading','Visitor stats')
@section('content')
<h1 class="title">Visitor stats</h1><p class="subtle">How many visitors came and where they came from &mdash; URL, IP, and source.</p>
<div class="grid stats" style="margin:1.5rem 0">
@foreach($counts as $d => $c)<div class="card"><span class="subtle">Last {{ $d }} day{{ $d > 1 ? 's' : '' }}</span><div class="stat-value">{{ $c['visitors'] }} <span style="font-size:.9rem;color:var(--muted);font-weight:600">visitors</span></div><div class="subtle">{{ $c['views'] }} page views</div></div>@endforeach
</div>
<div class="grid two-col" style="margin:1rem 0">
<section class="card"><h2 style="margin-top:0">By source &middot; 30 days</h2>@forelse($sourceBreakdown as $s)<div style="display:flex;justify-content:space-between;gap:1rem;padding:.55rem 0;border-bottom:1px solid var(--line)"><span style="text-transform:capitalize">{{ $s->source }}</span><strong>{{ $s->total }} <span style="font-weight:500;color:var(--muted)">({{ $s->visitors }} visitors)</span></strong></div>@empty<p class="subtle">No source data yet.</p>@endforelse</section>
<aside class="card"><h2>Top pages &middot; 30 days</h2>@forelse($topPages as $page)<div style="display:flex;justify-content:space-between;gap:1rem;padding:.55rem 0;border-bottom:1px solid var(--line)"><span style="overflow:hidden;text-overflow:ellipsis">{{ $page->url }}</span><strong>{{ $page->total }}</strong></div>@empty<p class="subtle">No page-view data yet.</p>@endforelse</aside>
</div>
<form class="toolbar" method="GET"><div class="field"><label>Search</label><input class="input" name="search" value="{{ request('search') }}" placeholder="URL, IP, referrer&hellip;"></div><div class="field"><label>Source</label><select class="select" name="source"><option value="all">All sources</option>@foreach($sources as $s)<option value="{{ $s }}" @selected(request('source') === $s)>{{ ucfirst($s) }}</option>@endforeach</select></div><div class="field"><label>Period</label><select class="select" name="range"><option value="30" @selected(request('range','30') == 30)>Last 30 days</option><option value="7" @selected(request('range') == 7)>Last 7 days</option><option value="3" @selected(request('range') == 3)>Last 3 days</option><option value="1" @selected(request('range') == 1)>Last 24 hours</option></select></div><button class="btn btn-primary">Filter</button></form>
<div class="card table-wrap"><table class="table"><thead><tr><th>Time</th><th>IP</th><th>URL</th><th>Source</th><th>Referrer</th><th>User agent</th></tr></thead><tbody>@forelse($pageViews as $v)<tr><td>{{ $v->created_at?->format('d M Y H:i') }}</td><td>{{ $v->ip_address }}</td><td>{{ $v->url }}</td><td><span class="badge">{{ ucfirst($v->source ?? 'direct') }}</span></td><td style="max-width:260px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">{{ $v->referrer ?? '&mdash;' }}</td><td style="max-width:220px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">{{ $v->user_agent }}</td></tr>@empty<tr><td colspan="6">No visitor activity recorded.</td></tr>@endforelse</tbody></table></div>{{ $pageViews->links() }}
@endsection
