@extends('layouts.app')
@section('title', 'Checkout')
@push('styles')
<style>.checkout{display:grid;grid-template-columns:1.35fr .65fr;gap:2rem}.panel{border:1px solid #eee;border-radius:18px;padding:1.5rem}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.field{display:grid;gap:.35rem}.field.full{grid-column:1/-1}.field label{font-weight:700}.field input,.field textarea,.field select{padding:.75rem;border:1px solid #d1d5db;border-radius:9px;width:100%}.field textarea{min-height:100px}.payment-help{grid-column:1/-1;padding:1rem;border-radius:10px;background:#f7f4ef;border:1px solid #e7ded2;line-height:1.6}.payment-help[hidden]{display:none}.place{width:100%;padding:1rem;border:0;border-radius:10px;background:var(--brand-600);color:#fff;font-weight:800;font-size:1rem}.line{display:flex;justify-content:space-between;gap:1rem;padding:.6rem 0;border-bottom:1px solid #eee}@media(max-width:720px){.checkout{grid-template-columns:1fr}.form-grid{grid-template-columns:1fr}.field.full{grid-column:auto}}</style>
@endpush
@section('content')
<main class="container section-gap"><h1>Secure checkout</h1>
@if($errors->any())
<div class="alert alert-error" role="alert" aria-live="assertive"><strong>Please check your checkout details.</strong><ul style="margin:.5rem 0 0;padding-left:1.2rem">@foreach($errors->all() as $message)<li>{{ $message }}</li>@endforeach</ul></div>
@endif<form method="POST" action="{{ route('checkout.store') }}" class="checkout">@csrf
<section class="panel"><h2>Delivery details</h2><div class="form-grid">
<div class="field"><label for="name">Full name</label><input id="name" name="name" placeholder="Fatima" value="{{ old('name',auth()->user()?->name) }}" required></div>
<div class="field"><label for="email">Email</label><input id="email" type="email" name="email" placeholder="mail@gmail.com" value="{{ old('email',auth()->user()?->email) }}" required></div>
<div class="field"><label for="phone">Phone</label><input id="phone" name="phone" value="{{ old('phone',auth()->user()?->phone) }}" required></div>
<div class="field"><label for="shipping_method">Delivery method</label><select id="shipping_method" name="shipping_method" required>@foreach($shippingMethods as $method)<option value="{{ $method->code }}" @selected(old('shipping_method')===$method->code)>{{ $method->name }} — {{ $method->charge_type === 'free' ? 'Free' : '৳'.number_format((float)$method->base_charge,0) }}</option>@endforeach</select></div>
<div class="field"><label for="payment_method">Payment</label><select id="payment_method" name="payment_method" required>@foreach($paymentMethods as $method)<option value="{{ $method->code }}" data-instructions="{{ $method->instructions }}" data-account-name="{{ $method->account_name }}" data-account-number="{{ $method->account_number }}" @selected(old('payment_method')===$method->code)>{{ $method->name }}</option>@endforeach</select></div>
<div id="payment-help" class="payment-help" aria-live="polite" hidden><strong>Payment instructions</strong><div id="payment-help-text"></div></div>
<div class="field"><label for="district">District</label><input id="district" name="district" value="{{ old('district') }}" required></div><div class="field"><label for="thana">Thana</label><input id="thana" name="thana" value="{{ old('thana') }}" required></div>
<div class="field"><label for="post_office">Post office</label><input id="post_office" name="post_office" value="{{ old('post_office') }}" required></div><div class="field"><label for="post_code">Post code</label><input id="post_code" name="post_code" inputmode="numeric" value="{{ old('post_code') }}" required></div>
<div class="field full"><label for="address">Shipping address</label><textarea id="address" name="address" required>{{ old('address') }}</textarea></div><div class="field full"><label for="coupon_code">Coupon code (optional)</label><input id="coupon_code" name="coupon_code" value="{{ old('coupon_code') }}"></div></div></section>
<aside class="panel">@php $subtotal = 0; @endphp<h2>Your order</h2>@foreach($items as $item) @php $product=is_array($item)?$item['product']:$item->product; $variant=is_array($item)?$item['variant']:$item->productVariant; $quantity=is_array($item)?$item['quantity']:$item->quantity; $unitPrice=(float)($variant?->effective_price??$product->effective_price); $lineTotal=$unitPrice*$quantity; $subtotal+=$lineTotal; @endphp <div class="line"><span>{{ $product->name }} × {{ $quantity }}</span><strong>৳{{ number_format($lineTotal,0) }}</strong></div>@endforeach<div class="line"><strong>Subtotal</strong><strong>৳{{ number_format($subtotal,0) }}</strong></div><p style="font-size:.85rem;color:var(--text-muted)">The final total, coupon discount, and delivery charge are recalculated on the server.</p><button class="place" type="submit">Place order</button></aside></form></main>
@endsection
@push('scripts')
<script>document.addEventListener('DOMContentLoaded',()=>{const s=document.getElementById('payment_method'),b=document.getElementById('payment-help'),t=document.getElementById('payment-help-text');const update=()=>{const o=s.options[s.selectedIndex],p=[];if(o.dataset.instructions)p.push(o.dataset.instructions);if(o.dataset.accountName)p.push(`Account name: ${o.dataset.accountName}`);if(o.dataset.accountNumber)p.push(`Account number: ${o.dataset.accountNumber}`);t.textContent='';p.forEach((v,i)=>{t.append(document.createTextNode(v));if(i<p.length-1)t.append(document.createElement('br'))});b.hidden=p.length===0};s.addEventListener('change',update);update()});</script>
@endpush