@extends('layouts.admin')
@section('title','Order '.($order->order_number ?: '#'.$order->id))
@section('heading','Order details')
@section('content')
<div style="display:flex;justify-content:space-between;align-items:start;gap:1rem"><div><h1 class="title">{{ $order->order_number ?: '#'.$order->id }}</h1><p class="subtle">Placed {{ $order->created_at?->format('d M Y, g:i A') }}</p></div><span class="badge">{{ $order->order_status }}</span></div>
<div class="grid two-col" style="margin-top:1.5rem">
<div class="grid"><section class="card"><h2>Items</h2><div class="table-wrap"><table class="table"><thead><tr><th>Product</th><th>SKU</th><th>Qty</th><th>Price</th><th>Total</th></tr></thead><tbody>@foreach($order->items as $item)<tr><td>{{ $item->product_name ?: 'Legacy product' }}</td><td>{{ $item->product_sku ?: '—' }}</td><td>{{ $item->quantity }}</td><td>৳{{ number_format((float)$item->price,0) }}</td><td>৳{{ number_format((float)($item->line_total ?: $item->price*$item->quantity),0) }}</td></tr>@endforeach</tbody></table></div><div style="margin-left:auto;max-width:320px"><p style="display:flex;justify-content:space-between"><span>Subtotal</span><strong>৳{{ number_format((float)$order->subtotal_amount,0) }}</strong></p><p style="display:flex;justify-content:space-between"><span>Discount</span><strong>−৳{{ number_format((float)$order->discount_amount,0) }}</strong></p><p style="display:flex;justify-content:space-between"><span>Shipping</span><strong>৳{{ number_format((float)$order->shipping_charge,0) }}</strong></p><p style="display:flex;justify-content:space-between;font-size:1.15rem"><span>Total</span><strong>৳{{ number_format((float)$order->total_amount,0) }}</strong></p></div></section>
<section class="card"><h2>Status history</h2>@forelse($order->statusHistories as $history)<div style="border-left:3px solid var(--brand);padding:0 0 1rem 1rem"><strong>{{ $history->from_status ?: 'Created' }} → {{ $history->to_status }}</strong><div class="subtle">{{ $history->created_at?->format('d M Y, g:i A') }}</div>@if($history->note)<p>{{ $history->note }}</p>@endif</div>@empty<p class="subtle">No status transitions recorded.</p>@endforelse</section></div>
<aside class="grid"><section class="card"><h2>Customer</h2><p><strong>{{ $order->customer_name }}</strong><br>{{ $order->email }}<br>{{ $order->phone }}</p><p>{{ $order->shipping_address }}</p></section><section class="card"><h2>Payment</h2><p>{{ $order->payment_method }} · <strong>{{ $order->payment_status }}</strong></p>@if($order->transaction_id)<p>Reference: {{ $order->transaction_id }}</p>@endif</section>@if(count($allowedNext))<section class="card"><h2>Update status</h2><form method="POST" action="{{ route('admin.orders.updateStatus',$order) }}">@csrf<div class="field"><label>Next status</label><select class="select" name="to_status">@foreach($allowedNext as $status)<option>{{ $status }}</option>@endforeach</select></div><div class="field" style="margin-top:1rem"><label>Internal note</label><textarea class="textarea" name="note"></textarea></div><button class="btn btn-primary" style="margin-top:1rem">Update order</button></form></section>@endif</aside>
</div>
@endsection
