@extends('layouts.admin') @section('title',$product->exists?'Edit product':'Add product') @section('heading','Products') @section('content')
<h1 class="title">{{ $product->exists?'Edit product':'Add product' }}</h1><form class="card form-grid" style="margin-top:1rem" method="POST" enctype="multipart/form-data" action="{{ $product->exists?route('admin.products.update',$product):route('admin.products.store') }}">@csrf @if($product->exists)@method('PUT')@endif
@foreach([['name','Name','text'],['slug','Slug','text'],['sku','SKU','text'],['price','Price','number'],['discount_price','Sale price','number'],['stock','Stock','number'],['sort_order','Display / hero order','number'],['badge_text','Badge','text'],['meta_title','SEO title','text']] as [$key,$label,$type])<div class="field"><label>{{ $label }}</label><input class="input" type="{{ $type }}" step="{{ str_contains($key,'price')?'0.01':'1' }}" name="{{ $key }}" value="{{ old($key,$product->$key) }}" {{ in_array($key,['name','slug','price','stock','sort_order'])?'required':'' }}></div>@endforeach
<div class="field"><label>Category</label><select class="select" name="category_id" required>@foreach($categories as $c)<option value="{{ $c->id }}" @selected(old('category_id',$product->category_id)==$c->id)>{{ $c->name }}</option>@endforeach</select></div>
<div class="field"><label>Brand</label><select class="select" name="brand_id"><option value="">No brand</option>@foreach($brands as $brand)<option value="{{ $brand->id }}" @selected(old('brand_id',$product->brand_id)==$brand->id)>{{ $brand->name }}</option>@endforeach</select></div><div class="field full"><label>Tags</label><select class="select" name="tag_ids[]" multiple size="4">@foreach($tags as $tag)<option value="{{ $tag->id }}" @selected(in_array($tag->id,old('tag_ids',$product->tags?->pluck('id')->all()??[])))>{{ $tag->name }}</option>@endforeach</select></div><div class="field full"><label>Description</label><div class="rich-toolbar"><button type="button" data-command="bold"><b>B</b></button><button type="button" data-command="italic"><i>I</i></button><button type="button" data-command="insertUnorderedList">List</button><button type="button" data-command="formatBlock" data-value="h3">Heading</button></div><div class="textarea rich-editor" contenteditable="true">{!! old('description',$product->description) !!}</div><textarea hidden name="description" class="rich-source">{{ old('description',$product->description) }}</textarea></div><div class="field full"><label>SEO description</label><textarea class="textarea" name="meta_description">{{ old('meta_description',$product->meta_description) }}</textarea></div>
<div class="field full"><label>Images (PNG, WebP, JPG; max 5MB each)</label><input class="input" type="file" name="images[]" multiple accept="image/png,image/webp,image/jpeg"></div><div class="full" style="display:flex;gap:1rem;flex-wrap:wrap">@foreach($product->images??[] as $img)<div><img src="{{ app(\App\Services\ProductImageResolver::class)->resolve($img->image_path) }}" alt="" style="width:90px;height:90px;object-fit:contain"><button class="btn btn-danger" form="image-{{ $img->id }}">Remove</button></div>@endforeach</div>
<div class="full" style="display:flex;gap:1.2rem;flex-wrap:wrap">@foreach(['is_active'=>'Active','is_featured'=>'Homepage hero','is_new'=>'New','is_preorder'=>'Preorder'] as $key=>$label)<label><input type="checkbox" name="{{ $key }}" value="1" @checked(old($key,$product->$key??($key==='is_active')))>{{ $label }}</label>@endforeach</div><div class="full"><button class="btn btn-primary">Save product</button></div></form>
@if($product->exists)@foreach($product->images as $img)<form id="image-{{ $img->id }}" method="POST" action="{{ route('admin.products.images.destroy',[$product,$img]) }}">@csrf @method('DELETE')</form>@endforeach@endif
@if($product->exists)<section class="card" style="margin-top:1rem"><h2>Variants</h2><form class="form-grid" method="POST" enctype="multipart/form-data" action="{{ route('admin.products.variants.store',$product) }}">@csrf @include('admin.products._variant-fields',['variant'=>new \App\Models\ProductVariant])<div class="full"><button class="btn btn-primary">Add variant</button></div></form>@foreach($product->variants as $variant)<form class="form-grid" style="border-top:1px solid var(--line);padding-top:1rem;margin-top:1rem" method="POST" enctype="multipart/form-data" action="{{ route('admin.products.variants.update',[$product,$variant]) }}">@csrf @method('PUT') @include('admin.products._variant-fields',['variant'=>$variant])<div class="full"><button class="btn btn-soft">Save variant</button> <button class="btn btn-danger" form="delete-variant-{{ $variant->id }}">Delete</button></div></form><form id="delete-variant-{{ $variant->id }}" method="POST" action="{{ route('admin.products.variants.destroy',[$product,$variant]) }}">@csrf @method('DELETE')</form>@endforeach</section>@endif
@endsection
@push('styles')<style>.rich-toolbar{display:flex;gap:.35rem;padding:.5rem;background:#f8fafc;border:1px solid #cbd5e1}.rich-toolbar button{padding:.35rem .65rem}.rich-editor{min-height:220px}</style>@endpush
@push('scripts')<script>document.querySelectorAll('.rich-editor').forEach((editor)=>{const source=editor.parentElement.querySelector('.rich-source');editor.closest('form').addEventListener('submit',()=>source.value=editor.innerHTML);editor.parentElement.querySelectorAll('[data-command]').forEach((button)=>button.addEventListener('click',()=>{editor.focus();document.execCommand(button.dataset.command,false,button.dataset.value||null)}))});</script>@endpush